### ISSUE TITLE
CcBox (and likely Cc) need 'static (or !Drop) bound for soundness

### ISSUE THREAD

**Issue by eternaleye** [fitzgen/bacon-rajan-cc#1]
In the presence of data with some stack-bound lifetime `'a` and a `Drop` implementation, when a cycle is collected after the stack frame has expired then `Drop::drop()` may access invalidated references with the lifetime `'a`.

This could be avoided by not running `Drop::drop()` _at all_ (as `mem::forget()` is safe, but running a late destructor on non-`'static` data is not), but as that leaks memory it is likely not a viable solution.

**Comment by fitzgen** [comment]
Added a `'static` bound. Thanks for the explanation!

**Comment by eternaleye** [comment]
Heh, the email reminded me of this - not running Drop::drop() may be valuable in some cases, so it might be worth adding a CcBox/Cc variant for that - possibly even one that runs Drop::drop() if a value is "eagerly" dropped at the end of its lifetime, but not if collected as part of a cycle.
