### ISSUE TITLE
Clarify Trace trait usage

### ISSUE THREAD

**Issue by jrmuizel** [fitzgen/bacon-rajan-cc#5]
The Trace implementation for CcBox doesn't call tracer, instead of the trait seems to rely on owner of the Cc to do this. Is this necessary? Shouldn't the derived implementation of Trace basically just be to call trace() on each of its members?

**Comment by fitzgen** [comment]
The `Trace` implementation should enumerate outgoing edges, not recursively follow them. The collector can then use an explicit stack instead of recursion. Don't remember if it actually does this or not though.
