### ISSUE TITLE
How to user #[derive(Trace)?]

### ISSUE THREAD

**Issue by In-line** [fitzgen/bacon-rajan-cc#8]
How to user #[derive(Trace)?] It seems that this derive isn't on crates.io

**Comment by jrmuizel** [comment]
Unfortunately, I haven't implemented a derive yet. It shouldn't be too hard to do using by using the `synstructure` crate.

**Comment by mystor** [comment]
If it's useful, a similar (but I believe more complex?) derive exists for `rust-gc`. It's pretty small: https://github.com/Manishearth/rust-gc/blob/4432f7d034107101688c77a097aa5285bda98e95/gc_derive/src/lib.rs

**Comment by jrmuizel** [comment]
Actually there is already a derive for this in https://github.com/fitzgen/bacon-rajan-cc/tree/master/derive
